version: "3.9"

services:

  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    container_name: backend
    build:
      context: ""
      dockerfile: Dockerfile
    command: sh ./entrypoint.sh
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: