# Generated by Django 4.2.4 on 2023-08-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerActivityAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverresponse',
            name='response_payload',
        ),
        migrations.AddField(
            model_name='serverresponse',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
