# Generated by Django 4.2.4 on 2023-08-14 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ServerActivityAnalyzer', '0002_remove_serverresponse_response_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
